"""empty message

Revision ID: 112c36edb17a
Revises: dd7cbe3bd5fe
Create Date: 2020-07-15 16:55:57.504723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112c36edb17a'
down_revision = 'dd7cbe3bd5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drives')
    op.drop_table('drivelog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivelog',
    sa.Column('drive_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), nullable=False),
    sa.Column('action_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE')
    )
    op.create_table('drives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=999), nullable=True),
    sa.Column('path', sa.VARCHAR(length=999), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('free_space', sa.INTEGER(), nullable=True),
    sa.Column('mounted', sa.BOOLEAN(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('mounted IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
